---
title: "avocado-cartel-analysis"
author: "Dorothy Davis & Jen Lee"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidyverse)
library(lubridate)

```

## Importing Data

```{r echo = True, message = FALSE, warning = FALSE}
# Need to have package magrittr checked and downloaded

tblDisplaced <-
  read_csv('./data/displaced-persons-mexico/displaced-persons-by-region.csv')

tblOpiods<-
  read_csv('./data/opioid-crisis-by-interpersonal-relationships/Master_Table_Long.csv')

tblOpiods2<- 
  read_csv('./data/VSRR_Provisional_Drug_Overdose_Death_Counts.csv')

tblHomicidesFemale<-
  read_csv('./data/homicides-female/intentional-homicides-female.csv')

tblHomicidesMale<-
  read_csv('./data/homicides-male/intentional-homicides-male.csv')

tblHomicidesMexico<-
  read_csv('./data/homicides-mexico.csv')

tblAvocado<-
  read_csv('./data/avocado.csv')
```

Graphing Displaced

```{r}

tblDisplacedClean <- filter(tblDisplaced,  Country_Code  == 'MEX')
y <- select(tblDisplacedClean, 'Country_Code','2009':'2018')
disp <- data.frame(c(2009:2018), t(y[-1]))
colnames(disp) <- c('Date', y[, 1])

# Find the coefficients for line best fit
b<-lm(MEX~c(2009:2018),disp)$coefficients[1]
m<-lm(MEX~c(2009:2018),disp)$coefficients[2]

plotDisplaced<- ggplot(data = disp, x = 2009:2018, y = disp$'MEX') + geom_point(aes(x = 2009:2018, y = disp$'MEX')) + ggtitle('Displaced Persons in Mexico 2009-2018') + labs(x = 'years', y = 'number displaced') + geom_abline(aes(slope= m, intercept=b), color="orange") 
plotDisplaced
#Used https://stackoverflow.com/questions/33643181/how-do-i-flip-rows-and-columns-in-r/33643244
```

Graphing Opiods

```{r}
#Filtering data to find total deaths per each category. This isn't filtering to just these demographics, it's just pulling the total for each overall group. 
#tblOpiodsClean<- filter(tblOpiods, EducationType == 'Less Than HS' & CommuteType == 'Alone' & GDPType == 'All industry total')
tblOpiodsClean<- filter(tblOpiods, CommuteType == 'Alone' & GDPType == 'All industry total')
y<- select(tblOpiodsClean,'Year','Type','CountByType')
y[is.na(y)] <- 0
y<- filter(y, Type != 0)
y<-y %>%
    group_by(Year,Type) %>% 
    summarise_each(funs(sum))
yHeroin<- filter(y, Type == 'Heroin')
yOther<- filter(y, Type == 'Other Opiod')
yHeroin
plotOpiods<- ggplot(data = yHeroin, aes(x = 2011:2017, y = yHeroin$CountByType)) + geom_point(aes(x = 2011:2017, y = yHeroin$CountByType, color = 'blue')) 
plotOpiods <- plotOpiods + geom_point(data = yOther, aes(x = 2011:2017, y = yOther$CountByType, color = 'red')) + labs(x = 'years', y = 'total deaths') 
# Adding Legend
plotOpiods <- plotOpiods + scale_color_manual(labels = c("Heroin", "Other Opiods"), values = c("blue", "red"))
plotOpiods


#Used https://stackoverflow.com/questions/8161836/how-do-i-replace-na-values-with-zeros-in-an-r-dataframe
#https://stackoverflow.com/questions/34523679/aggregate-multiple-columns-at-once
```

Graphing Opiods from CDC Data Source
```{r}
tblOpiodsClean2<- filter(tblOpiods2, Indicator == 'Heroin (T40.1)' | Indicator == 'Natural & semi-synthetic opioids (T40.2)' | Indicator == 'Opioids (T40.0-T40.4,T40.6)' | Indicator == 'Natural & semi-synthetic opioids, incl. methadone (T40.2, T40.3)' | Indicator == 'Natural, semi-synthetic, & synthetic opioids, incl. methadone (T40.2-T40.4)')

y<- data.frame(select(tblOpiodsClean2, 'State', 'Year', 'Month', 'Indicator', 'Data_Value'))
y[is.na(y)] <- 0

y_temp <- y[which(y$State == 'US'), ]
#y_temp <- y

y_temp <- cbind(y_temp, date=rep(NA, nrow(y_temp)))

for (i in 1:length(y_temp)) {
  y_temp[i]$date = parse_date(paste(y_temp$Year, y_temp$Month, sep="-"), format='%Y-%B')
  #print(parse_date(paste(y_temp$Year, y_temp$Month, sep="-"), format='%Y-%B'))
}

yHeroin2<-filter(y_temp, Indicator == 'Heroin (T40.1)')
yOpiods2<-filter(y_temp, Indicator == 'Opioids (T40.0-T40.4,T40.6)')


plotOpiods2<- ggplot(data = yHeroin2, aes(x = yHeroin2$date, y = yHeroin2$Data_Value)) + geom_point(aes(x = yHeroin2$date, y = yHeroin2$Data_Value, color = 'blue')) 
#plotOpiods2 <- plotOpiods2 + geom_point(data = yOpiods2, aes(x = yOpiods2$date, y = yOpiods2$Data_Value, color = 'red')) + labs(x = 'years', y = 'total deaths') 
# Adding Legend
#plotOpiods2 <- plotOpiods2 + scale_color_manual(labels = c("Heroin", "Other Opiods"), values = c("blue", "red"))
plotOpiods2

```



Graphing Avocados

```{r}
tblAvocadoClean<- select(tblAvocado, 'Date','AveragePrice')
y<-data.frame(tblAvocadoClean %>%
    group_by(Date) %>% 
    summarise_each(funs(mean)))
plotAvocado<- ggplot(y, aes(x = y$Date, y = y$AveragePrice)) + geom_jitter(aes(x = y$Date, y = y$AveragePrice))
plotAvocado

curr_year <- 2015
years <- c(2015)
avg_prices <- c()
prices <- c()
# Group avacado data by year
for (i in 1:nrow(y)) {
  row <- y[i, ]
  if (as.integer(substring(row$Date, 1, 4)) == curr_year) {
    prices <- c(prices, row$AveragePrice)
  } else {
    curr_year <- curr_year + 1
    years <- c(years, curr_year)
    avg_prices <- c(avg_prices, mean(prices))
  }
}
# Catch the last one
avg_prices <- c(avg_prices, mean(prices))

avocados_annual <- data.frame(years, avg_prices)
colnames(avocados_annual) <- names(y)

# Much less exciting but may be useful for the data we only have on years
plotAvocado_ann<- ggplot(avocados_annual, aes(x = avocados_annual$Date, y = avocados_annual$AveragePrice)) + geom_point()
plotAvocado_ann
```


Graphing Avocados With New Data

```{r echo = True, message = FALSE, warning = FALSE}
tblAvocadoNew<-
  read_csv('./data/avocado_complete.csv')
tblAvocadoNew$Date<-as.Date(tblAvocadoNew$Date)

tblAvocadoNew$Organic[is.na(tblAvocadoNew$Organic)] <- 'N'
tblAvocadoNew<-filter(tblAvocadoNew, Organic != 'Y' & Unit == 'each' & Variety == 'HASS' & Date > as.Date('2015-04-01') & Date < as.Date ('2019-07-01'))

years<- year(tblAvocadoNew$Date)
months<- month(tblAvocadoNew$Date)

tblAvocadoNew$years<- years
tblAvocadoNew$months<- months

y<-data.frame(select(tblAvocadoNew, 'months', 'years', 'Weighted_Avg_Price') %>%
    group_by(years, months) %>% 
      summarise(mean = mean(Weighted_Avg_Price)))

y$date<- seq.Date(as.Date('2015-04-01'),as.Date('2019-6-28'), by = 'month')

g <- ggplot(data = y) + geom_point(aes(x = date, y = mean)) + geom_smooth(aes(x = date, y = mean))
g


#Below is annual graph just in case we still need it
#avocadoPrices$years <- c(2008:2018)
#avocadoPrices$prices<-tapply(tblAvocadoNew$Weighted_Avg_Price, years, mean)

#g <- ggplot(data = avocadoPrices, aes(x=2008:2018)) + geom_point(aes(x = 2008:2018, y = avocadoPrices$prices))
#g

#https://stackoverflow.com/questions/27298593/reading-csv-file-in-r-and-formatting-dates-and-time-while-reading-and-avoiding-m
#https://blog.exploratory.io/filter-with-date-function-ce8e84be680  
#https://stackoverflow.com/questions/28143510/r-group-by-year
```


Graphing Homicides
```{r}
hom_temp <- data.frame(tblHomicidesMexico)
hom <- NULL

# Turn into a vertical data frame
for (r in 1:nrow(hom_temp)) {
  year <- hom_temp[r, 1]
  for (m in 1:12) {
    date <- paste(year, m, sep='-')
    #UGH I'm not sure why the date is loading weird 
    #hom <- data.frame(rbind(hom, c(date, hom_temp[r, m+2])))
    hom <- data.frame(rbind(hom, c(parse_date(date, format='%Y-%m'), hom_temp[r, m+2])))
  }
}

colnames(hom)<- c('Date', 'Homicides')

plotHomicidesMexico <- ggplot(data = hom, x = hom$Date, y = hom$Homicides) + geom_point(aes(x = hom$Date, y = hom$Homicides))
plotHomicidesMexico

```

Graphing Homocides Female

```{r}
tblHomicidesFemaleClean <- filter(tblHomicidesFemale,  Country_Code  == 'MEX')
y <- select(tblHomicidesFemaleClean, 'Country_Code','2009':'2018')
hom.f <- data.frame(c(2009:2018), t(y[-1]))
colnames(hom.f) <- c('Year', y[, 1])

# Find the coefficients for line best fit
b<-lm(MEX~c(2009:2018),hom.f)$coefficients[1]
m<-lm(MEX~c(2009:2018),hom.f)$coefficients[2]

plotDisplaced<- ggplot(data = hom.f, x = 2009:2018, y = hom.f$'MEX') + geom_point(aes(x = 2009:2018, y = hom.f$'MEX')) + ggtitle('Female Homicides Mexico 2009-2018') + labs(x = 'years', y = 'Intentional homicides, female (per 100,000 female)') + geom_abline(aes(slope= m, intercept=b), color="orange") 
plotDisplaced

```



Graphing Homocides Male

```{r}
tblHomicidesMaleClean <- filter(tblHomicidesMale,  Country_Code  == 'MEX')
y <- select(tblHomicidesMaleClean, 'Country_Code','2009':'2018')
hom.m <- data.frame(c(2009:2018), t(y[-1]))
colnames(hom.m) <- c('Year', y[, 1])

# Find the coefficients for line best fit
b<-lm(MEX~c(2009:2018),hom.m)$coefficients[1]
m<-lm(MEX~c(2009:2018),hom.m)$coefficients[2]

plotDisplaced<- ggplot(data = hom.m, x = 2009:2018, y = hom.m$'MEX') + geom_point(aes(x = 2009:2018, y = hom.m$'MEX')) + ggtitle('Male Homicides Mexico 2009-2018') + labs(x = 'years', y = 'Intentional homicides, male (per 100,000 male)') + geom_abline(aes(slope= m, intercept=b), color="orange") 
plotDisplaced

```


```{r}
# Add 2018 NA to missing datasets
yHeroin[nrow(yHeroin)+1,] <- c(2018, 'Heroin', NA)
yOther[nrow(yOther)+1,] <- c(2018, 'Other Opiod', NA)


master_data <- data.frame(avocados_annual$Date, avocados_annual$AveragePrice, subset(disp, Date %in% c(2015:2018))$MEX, subset(yHeroin, Year %in% c(2015:2018))$CountByType, subset(yOther, Year %in% c(2015:2018))$CountByType, subset(hom.f, Year %in% c(2015:2018))$MEX, subset(hom.m, Year %in% c(2015:2018))$MEX)
colnames(master_data) <- c('year', 'avocado_prices', 'displaced_persons', 'heroin', 'other_opiods', 'female_homicides', 'male_homicides')
master_data
````


